# Generated by Django 5.0.1 on 2024-02-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_product_alter_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
